#!/usr/bin/php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

use Cap\Command\CapCommand;

$application = new Application();
$application->add(new CapCommand());
$application->run();
